### ISSUE TITLE
Contribution coins

### ISSUE THREAD

**Issue by gordonmattey** [jeffward01/Chaincoin-MN-SetupScript#2]
Max wants to ask people to send their generated coins to a central wallet to fund marketing and other expenses.

It would be cool if the script also let you provide an option to contribute to the central contribution wallet, which we'd have to get the address for, but everyone sends to the same wallet.

**Comment by jeffward01** [comment]
> Max wants to ask people to send their generated coins to a central wallet to fund marketing and other expenses.

Just so I understand, Max of 'High On Coins' requested that people send their 'earned' CHC coins to a central wallet?

-------------------------

> It would be cool if the script also let you provide an option to contribute to the central contribution wallet, which we'd have to get the address for, but everyone sends to the same wallet.

Sure we can do that, that will be a new 'feature' tho.  What we can do is write a new BASH file or expand on this existing BASH file that listens for arriving CHC rewards, and once X amount of CHC coins are 'rewarded'.  It will generate a transaction to the central wallet.

This feature request is more of a 'service' than a script.  Alternatively to a bash script that stays 'on' in the background, we can also write a Python/JavaScript script that will do the same thing

Is this what you have in mind? Is this something you can build? I am a bit pressed for time at the moment but can create it myself too if the demand is high enough

**Comment by jeffward01** [comment]
Since no response/activity has been received I am closing this issue until the issue is raised again
